fix(deps): Bump axios from 1.7.4 to 1.7.5 (#371)
[//]: # (dependabot-start)
⚠️  **Dependabot is rebasing this PR** ⚠️ 

Rebasing might not happen immediately, so don't worry if this takes some time.

Note: if you make any changes to this PR yourself, they will take precedence over the rebase.

---

[//]: # (dependabot-end)

Bumps [axios](https://github.com/axios/axios) from 1.7.4 to 1.7.5.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/axios/axios/releases">axios's releases</a>.</em></p>
<blockquote>
<h2>Release v1.7.5</h2>
<h2>Release notes:</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>adapter:</strong> fix undefined reference to hasBrowserEnv (<a href="https://redirect.github.com/axios/axios/issues/6572">#6572</a>) (<a href="https://github.com/axios/axios/commit/7004707c4180b416341863bd86913fe4fc2f1df1">7004707</a>)</li>
<li><strong>core:</strong> add the missed implementation of AxiosError#status property; (<a href="https://redirect.github.com/axios/axios/issues/6573">#6573</a>) (<a href="https://github.com/axios/axios/commit/6700a8adac06942205f6a7a21421ecb36c4e0852">6700a8a</a>)</li>
<li><strong>core:</strong> fix <code>ReferenceError: navigator is not defined</code> for custom environments; (<a href="https://redirect.github.com/axios/axios/issues/6567">#6567</a>) (<a href="https://github.com/axios/axios/commit/fed1a4b2d78ed4a588c84e09d32749ed01dc2794">fed1a4b</a>)</li>
<li><strong>fetch:</strong> fix credentials handling in Cloudflare workers (<a href="https://redirect.github.com/axios/axios/issues/6533">#6533</a>) (<a href="https://github.com/axios/axios/commit/550d885eb90fd156add7b93bbdc54d30d2f9a98d">550d885</a>)</li>
</ul>
<h3>Contributors to this release</h3>
<ul>
<li><!-- raw HTML omitted --> <a href="https://github.com/DigitalBrainJS" title="+187/-83 ([#6573](https://github.com/axios/axios/issues/6573) [#6567](https://github.com/axios/axios/issues/6567) [#6566](https://github.com/axios/axios/issues/6566) [#6564](https://github.com/axios/axios/issues/6564) [#6563](https://github.com/axios/axios/issues/6563) [#6557](https://github.com/axios/axios/issues/6557) [#6556](https://github.com/axios/axios/issues/6556) [#6555](https://github.com/axios/axios/issues/6555) [#6554](https://github.com/axios/axios/issues/6554) [#6552](https://github.com/axios/axios/issues/6552) )">Dmitriy Mozgovoy</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/antoninbas" title="+6/-6 ([#6572](https://github.com/axios/axios/issues/6572) )">Antonin Bas</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/hansottowirtz" title="+4/-1 ([#6533](https://github.com/axios/axios/issues/6533) )">Hans Otto Wirtz</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/axios/axios/blob/v1.x/CHANGELOG.md">axios's changelog</a>.</em></p>
<blockquote>
<h2><a href="https://github.com/axios/axios/compare/v1.7.4...v1.7.5">1.7.5</a> (2024-08-23)</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>adapter:</strong> fix undefined reference to hasBrowserEnv (<a href="https://redirect.github.com/axios/axios/issues/6572">#6572</a>) (<a href="https://github.com/axios/axios/commit/7004707c4180b416341863bd86913fe4fc2f1df1">7004707</a>)</li>
<li><strong>core:</strong> add the missed implementation of AxiosError#status property; (<a href="https://redirect.github.com/axios/axios/issues/6573">#6573</a>) (<a href="https://github.com/axios/axios/commit/6700a8adac06942205f6a7a21421ecb36c4e0852">6700a8a</a>)</li>
<li><strong>core:</strong> fix <code>ReferenceError: navigator is not defined</code> for custom environments; (<a href="https://redirect.github.com/axios/axios/issues/6567">#6567</a>) (<a href="https://github.com/axios/axios/commit/fed1a4b2d78ed4a588c84e09d32749ed01dc2794">fed1a4b</a>)</li>
<li><strong>fetch:</strong> fix credentials handling in Cloudflare workers (<a href="https://redirect.github.com/axios/axios/issues/6533">#6533</a>) (<a href="https://github.com/axios/axios/commit/550d885eb90fd156add7b93bbdc54d30d2f9a98d">550d885</a>)</li>
</ul>
<h3>Contributors to this release</h3>
<ul>
<li><!-- raw HTML omitted --> <a href="https://github.com/DigitalBrainJS" title="+187/-83 ([#6573](https://github.com/axios/axios/issues/6573) [#6567](https://github.com/axios/axios/issues/6567) [#6566](https://github.com/axios/axios/issues/6566) [#6564](https://github.com/axios/axios/issues/6564) [#6563](https://github.com/axios/axios/issues/6563) [#6557](https://github.com/axios/axios/issues/6557) [#6556](https://github.com/axios/axios/issues/6556) [#6555](https://github.com/axios/axios/issues/6555) [#6554](https://github.com/axios/axios/issues/6554) [#6552](https://github.com/axios/axios/issues/6552) )">Dmitriy Mozgovoy</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/antoninbas" title="+6/-6 ([#6572](https://github.com/axios/axios/issues/6572) )">Antonin Bas</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/hansottowirtz" title="+4/-1 ([#6533](https://github.com/axios/axios/issues/6533) )">Hans Otto Wirtz</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/axios/axios/commit/59cd6b0dece4050b190717a7c5cdf77906ce2104"><code>59cd6b0</code></a> chore(release): v1.7.5 (<a href="https://redirect.github.com/axios/axios/issues/6574">#6574</a>)</li>
<li><a href="https://github.com/axios/axios/commit/6700a8adac06942205f6a7a21421ecb36c4e0852"><code>6700a8a</code></a> fix(core): add the missed implementation of AxiosError#status property; (<a href="https://redirect.github.com/axios/axios/issues/6573">#6573</a>)</li>
<li><a href="https://github.com/axios/axios/commit/7004707c4180b416341863bd86913fe4fc2f1df1"><code>7004707</code></a> fix(adapter): fix undefined reference to hasBrowserEnv (<a href="https://redirect.github.com/axios/axios/issues/6572">#6572</a>)</li>
<li><a href="https://github.com/axios/axios/commit/fed1a4b2d78ed4a588c84e09d32749ed01dc2794"><code>fed1a4b</code></a> fix(core): fix <code>ReferenceError: navigator is not defined</code> for custom environm...</li>
<li><a href="https://github.com/axios/axios/commit/550d885eb90fd156add7b93bbdc54d30d2f9a98d"><code>550d885</code></a> fix(fetch): fix credentials handling in Cloudflare workers (<a href="https://redirect.github.com/axios/axios/issues/6533">#6533</a>)</li>
<li><a href="https://github.com/axios/axios/commit/bcd1c6d65ada866b732c1ffabe6940f99b12d702"><code>bcd1c6d</code></a> chore(actions): fix sponsor action; (<a href="https://redirect.github.com/axios/axios/issues/6566">#6566</a>)</li>
<li><a href="https://github.com/axios/axios/commit/c8b7be59cba56e8fd09dc667de246117987d7517"><code>c8b7be5</code></a> chore(action): exclude <code>sponsors</code> branch from CI tests; (<a href="https://redirect.github.com/axios/axios/issues/6564">#6564</a>)</li>
<li><a href="https://github.com/axios/axios/commit/67aa1effe48c0dced70d139ea13e7d6dff734637"><code>67aa1ef</code></a> chore(sponsor): update sponsor block (<a href="https://redirect.github.com/axios/axios/issues/6559">#6559</a>)</li>
<li><a href="https://github.com/axios/axios/commit/ff254a5065f1aeb50a62b9e3f16290d6d501c78d"><code>ff254a5</code></a> chore(action): change sponsors uri origin; (<a href="https://redirect.github.com/axios/axios/issues/6563">#6563</a>)</li>
<li><a href="https://github.com/axios/axios/commit/4f99675fe7eae503422f932b9407242dbc1b7d55"><code>4f99675</code></a> chore(sponsor): update sponsor block (<a href="https://redirect.github.com/axios/axios/issues/6558">#6558</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/axios/axios/compare/v1.7.4...v1.7.5">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=axios&package-manager=npm_and_yarn&previous-version=1.7.4&new-version=1.7.5)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>